# Update the version paramater the following:
# major are: big changes as multiple new mods/resourcepacks/shaders/configs etc. 
# minor are: new content mods 
# patch are: mod updates, new performance mods or config changes

name = "Winterlands"
author = "Zacklack"
version = "3.5.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86fb972d46d5768be13ed4b89b2430b416e4a5aac53d97351eace978368cc1a9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
