name = "Winterlands"
author = "Zacklack"
version = "4.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d66b66266958f34fa7f320167977cbc09e379d06163d7708f63b46d3372f00a7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
