name = "Winterlands"
author = "Zacklack"
version = "4.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "704821e17ae48e1ff6a85a96dc2721e8378cedc1e0c989c986a3918b9b775839"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
