name = "Winterlands"
author = "Zacklack"
version = "4.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99314d2b284a841486c1c774f210d81b014b49166ea393f90aa8bec65cee952c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
