name = "Winterlands"
author = "Zacklack"
version = "4.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9d152587b47730fc05c9afd13e2d494db86b9cb0970d7d7b0e20bca91166807"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
