name = "Winterlands"
author = "Zacklack"
version = "4.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc42d18a58f9280a44ffe910e776785904aa95b7fe4875be6d8a795f59992033"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
