name = "Winterlands"
author = "Zacklack"
version = "4.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "230b6f94517d12ce14539c3f88e274ea18d4012639ebf70518aa46e465d6552e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
