name = "Winterlands"
author = "Zacklack"
version = "4.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95a7caf660f6302d89b607db4025d284556b0556961a9659c0a3b28b9977520f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
