name = "Winterlands"
author = "Zacklack"
version = "1.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2342334b2ba0df5e3850296eaec1384bf6308d6e4a8de56aa15a7dbee7355583"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
