name = "Winterlands"
author = "Zacklack"
version = "4.1.4"
description = "A cozy winter and slightly Christmas-themed Modpack, perfect for the classic 2-week Minecraft phase in winter."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "511d9193201f8e651eb92bbd9b161a36da8c5da9e80a88f203f1bda0aa648918"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"

[options]
datapack-folder = "config/paxi/datapacks"
