name = "Chillicord Winterlands"
author = "Zacklack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "43cf96d1af56966c80bcfd591da16639f4a0f69c497028acd8b21c8c1e1a3d5c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
