name = "Winterlands"
author = "Zacklack"
version = "1.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5a82d84f01c6bb119601b9fd662d256acc5a7e02da4919f1f783582b6e7038a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
