name = "Winterlands"
author = "Zacklack"
version = "4.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ee235f6508924136029f9372f041481bce3f9c8c37ccac6f196e1f78d4d3258"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
