name = "Winterlands"
author = "Zacklack"
version = "3.6.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17f17793a174e1013d2c586d8ebbbbde01f1f1aa53dbe74d84700daf91161368"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
