name = "Winterlands"
author = "Zacklack"
version = "4.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a23b6b2e67041b2062ec00c907359559abb8f1410e6e3dbc9296efc0f0c51ba7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
