name = "Winterlands"
author = "Zacklack"
version = "4.1.4"
description = "A cozy winter and slightly Christmas-themed Modpack, perfect for the classic 2-week Minecraft phase in winter."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb156ef5ec8552c4f03bb43801112563183e575a120ddefea58f60c08c95d238"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
datapack-folder = "config/paxi/datapacks"
