name = "Winterlands"
author = "Zacklack"
version = "1.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b993c88a2e8c5feb027f40cbc456ce4dba5a61d3d1920efa5e24c023c628e2da"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
