name = "Winterlands"
author = "Zacklack"
version = "4.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54330abae5dc1915f1d44a25bc3212643802f32bb4398870158306ee7875be88"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
