name = "Winterlands"
author = "Zacklack"
version = "4.1.4"
description = "A cozy winter and slightly Christmas-themed Modpack, perfect for the classic 2-week Minecraft phase in winter."
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "898c4f2069c3ea246466d2363c0ec29ee1aab409684e454ddcab932abe6827f8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
datapack-folder = "config/paxi/datapacks"
