name = "Winterlands"
author = "Zacklack"
version = "3.8.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "450122c012c0027a1307b9ba5fa663525b440310827ec734d92dc88253c70e92"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
