name = "Winterlands"
author = "Zacklack"
version = "1.0.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d0ca04faed162e572de889dd333f36c6043a27304871b7888e90c6accbd610a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
